/**
 * Generates TOEIC-style starter question JSON. Run once to refresh committed data:
 *   npx tsx prisma/scripts/generate-questions.ts
 */
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import type { SeedQuestion, QuestionCategory, Difficulty } from "../validate-questions";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "data", "questions");

type Q = Omit<SeedQuestion, "id"> & { id: string };

function mcq(
  id: string,
  category: QuestionCategory,
  difficulty: Difficulty,
  stem: string,
  correct: string,
  distractors: [string, string, string],
  explanation: string,
  hint: string,
  passage: string | null = null,
  audioUrl: string | null = null,
): Q {
  const labels = [correct, ...distractors];
  // Shuffle deterministically by id hash so committed JSON is stable
  const order = deterministicShuffle(labels, id);
  return {
    id,
    category,
    type: "MCQ",
    difficulty,
    stem,
    passage,
    audioUrl,
    explanation,
    hint,
    choices: order.map((label) => ({ label, isCorrect: label === correct })),
  };
}

function deterministicShuffle<T>(arr: T[], seed: string): T[] {
  const copy = [...arr];
  let h = 0;
  for (const c of seed) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  for (let i = copy.length - 1; i > 0; i--) {
    h = (h * 1664525 + 1013904223) >>> 0;
    const j = h % (i + 1);
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

const vocabulary: Q[] = [
  mcq("vocab-001", "VOCABULARY", "EASY", "The manager asked us to submit the report ___ Friday.", "by", ["at", "on", "since"], "'By Friday' means no later than Friday.", "Which preposition shows a deadline?"),
  mcq("vocab-002", "VOCABULARY", "EASY", "Please ___ the form before leaving the office.", "complete", ["compete", "complaint", "compile"], "'Complete' means to finish filling out.", "Which word means 'finish filling out'?"),
  mcq("vocab-003", "VOCABULARY", "EASY", "The new employee needs ___ training before starting.", "additional", ["addition", "additionally", "added"], "An adjective is needed before the noun 'training'.", "Look for the adjective form."),
  mcq("vocab-004", "VOCABULARY", "EASY", "Customers can ___ a refund within thirty days.", "request", ["require", "requesting", "requested"], "'Request' fits the modal 'can' + base verb pattern.", "Which verb means 'ask for'?"),
  mcq("vocab-005", "VOCABULARY", "EASY", "The conference room is ___ the elevator on the third floor.", "near", ["nearly", "nearest", "nearer"], "'Near' is a preposition showing location.", "Which word shows location?"),
  mcq("vocab-006", "VOCABULARY", "EASY", "We need to ___ the meeting because the director is traveling.", "postpone", ["prevent", "prepare", "promote"], "'Postpone' means to delay to a later time.", "Which word means 'delay'?"),
  mcq("vocab-007", "VOCABULARY", "EASY", "The invoice must be paid ___ receipt.", "upon", ["under", "above", "behind"], "'Upon receipt' is a fixed business phrase.", "Which preposition follows 'paid' in this idiom?"),
  mcq("vocab-008", "VOCABULARY", "EASY", "Her ___ to detail makes her an excellent proofreader.", "attention", ["attentive", "attend", "attended"], "A noun is needed after the possessive 'Her'.", "Which noun fits after 'Her'?"),
  mcq("vocab-009", "VOCABULARY", "EASY", "The company will ___ free lunch during the workshop.", "provide", ["providing", "provider", "provision"], "Future 'will' takes the base verb 'provide'.", "Base verb after 'will'."),
  mcq("vocab-010", "VOCABULARY", "EASY", "Please keep all confidential documents in a ___ place.", "secure", ["security", "securely", "secured"], "An adjective modifies the noun 'place'.", "Adjective before 'place'."),
  mcq("vocab-011", "VOCABULARY", "MEDIUM", "The board approved a ___ increase in the marketing budget.", "substantial", ["substance", "substantially", "substitute"], "'Substantial' means large or significant.", "Adjective modifying 'increase'."),
  mcq("vocab-012", "VOCABULARY", "MEDIUM", "Applicants must ___ three years of relevant experience.", "possess", ["possession", "possible", "possibly"], "'Possess' means to have or hold.", "Formal verb for 'have'."),
  mcq("vocab-013", "VOCABULARY", "MEDIUM", "The software update will ___ several known issues.", "resolve", ["resolution", "resolved", "resolving"], "'Resolve' means to fix or solve.", "Which verb means 'fix'?"),
  mcq("vocab-014", "VOCABULARY", "MEDIUM", "All employees are ___ to wear identification badges.", "required", ["require", "requirement", "requiring"], "Passive: 'are required to'.", "Past participle in passive."),
  mcq("vocab-015", "VOCABULARY", "MEDIUM", "The warehouse operates twenty-four hours a day on a ___ basis.", "continuous", ["continually", "continuation", "continue"], "'Continuous' describes uninterrupted operation.", "Adjective before 'basis'."),
  mcq("vocab-016", "VOCABULARY", "MEDIUM", "Mr. Tanaka's ___ was announced at this morning's staff meeting.", "promotion", ["promote", "promoted", "promotional"], "A noun is needed as the subject complement.", "Noun form of 'promote'."),
  mcq("vocab-017", "VOCABULARY", "MEDIUM", "The client expressed ___ with the delayed shipment.", "dissatisfaction", ["dissatisfy", "dissatisfied", "dissatisfying"], "Noun after 'expressed'.", "Noun form needed."),
  mcq("vocab-018", "VOCABULARY", "MEDIUM", "We cannot ___ the contract until legal review is finished.", "finalize", ["final", "finally", "finalization"], "'Finalize' means to complete the last steps.", "Verb meaning 'complete formally'."),
  mcq("vocab-019", "VOCABULARY", "MEDIUM", "The seminar focuses on ___ communication skills.", "effective", ["effect", "effectively", "effectiveness"], "Adjective modifying 'communication skills'.", "Adjective form."),
  mcq("vocab-020", "VOCABULARY", "MEDIUM", "Inventory levels are lower than ___ for this season.", "anticipated", ["anticipate", "anticipation", "anticipating"], "Comparative with past participle as adjective.", "Expected / foreseen."),
  mcq("vocab-021", "VOCABULARY", "HARD", "The merger will ___ both companies' market share.", "consolidate", ["consolidation", "consolidated", "consolidating"], "'Consolidate' means to combine and strengthen.", "Verb: combine into one stronger unit."),
  mcq("vocab-022", "VOCABULARY", "HARD", "Her proposal was met with ___ from the finance team.", "skepticism", ["skeptical", "skeptic", "skeptically"], "Noun after preposition 'with'.", "Noun: doubt or questioning."),
  mcq("vocab-023", "VOCABULARY", "HARD", "The audit revealed several ___ in the expense reports.", "discrepancies", ["discrepant", "discrepancy", "discrepantly"], "Plural noun after 'several'.", "Plural noun: inconsistencies."),
  mcq("vocab-024", "VOCABULARY", "HARD", "The CEO emphasized the need for ___ across all departments.", "accountability", ["accountable", "account", "accounting"], "Noun after 'for'.", "Noun: responsibility for actions."),
  mcq("vocab-025", "VOCABULARY", "HARD", "Regulations require firms to ___ data privacy standards.", "adhere to", ["adhere", "adapt to", "adopt"], "Phrasal verb 'adhere to' means follow rules.", "Fixed phrase with 'to'."),
  mcq("vocab-026", "VOCABULARY", "EASY", "The flight to Singapore has been ___ due to weather.", "delayed", ["delay", "delaying", "delays"], "Past participle as adjective after 'been'.", "Past participle describing status."),
  mcq("vocab-027", "VOCABULARY", "EASY", "Guests should ___ at the front desk upon arrival.", "register", ["registration", "registered", "registrar"], "Modal 'should' + base verb.", "Base verb after modal."),
  mcq("vocab-028", "VOCABULARY", "EASY", "The brochure contains ___ about local attractions.", "information", ["inform", "informative", "informed"], "Uncountable noun after 'contains'.", "Uncountable noun."),
  mcq("vocab-029", "VOCABULARY", "EASY", "Please ___ your seat belt before takeoff.", "fasten", ["fast", "fastened", "fastening"], "Imperative: base verb.", "Command form."),
  mcq("vocab-030", "VOCABULARY", "EASY", "The restaurant received excellent ___ from reviewers.", "reviews", ["reviewing", "reviewed", "reviewer"], "Plural noun as direct object.", "Plural noun matching 'excellent'."),
  mcq("vocab-031", "VOCABULARY", "MEDIUM", "The technician will ___ the equipment this afternoon.", "inspect", ["inspection", "inspector", "inspected"], "Future: 'will' + base verb.", "Base verb after 'will'."),
  mcq("vocab-032", "VOCABULARY", "MEDIUM", "Sales figures exceeded our most ___ projections.", "optimistic", ["optimism", "optimistically", "optimize"], "Superlative + adjective before noun.", "Adjective before 'projections'."),
  mcq("vocab-033", "VOCABULARY", "MEDIUM", "The handbook ___ guidelines for remote work.", "outlines", ["outline", "outlined", "outlining"], "Singular subject 'handbook' needs -s verb.", "Third-person singular verb."),
  mcq("vocab-034", "VOCABULARY", "MEDIUM", "We appreciate your ___ response to our inquiry.", "prompt", ["promptly", "promptness", "prompted"], "Adjective modifying 'response'.", "Adjective: quick."),
  mcq("vocab-035", "VOCABULARY", "MEDIUM", "The venue can ___ up to five hundred attendees.", "accommodate", ["accommodation", "accommodating", "accommodated"], "Modal 'can' + base verb.", "Verb: provide space for."),
  mcq("vocab-036", "VOCABULARY", "HARD", "The committee reached a ___ after lengthy negotiations.", "consensus", ["consent", "consensual", "consented"], "'Consensus' means general agreement.", "Noun: general agreement."),
  mcq("vocab-037", "VOCABULARY", "HARD", "Shareholders voted to ___ the proposed acquisition.", "ratify", ["ratification", "ratified", "ratifying"], "'Ratify' means to formally approve.", "Formal verb: approve officially."),
  mcq("vocab-038", "VOCABULARY", "HARD", "The policy aims to ___ workplace harassment.", "eliminate", ["elimination", "eliminated", "eliminating"], "Infinitive 'to' + base verb.", "Verb: remove completely."),
  mcq("vocab-039", "VOCABULARY", "HARD", "Managers must ensure ___ treatment of all staff.", "equitable", ["equity", "equitably", "equal"], "'Equitable' means fair and impartial.", "Adjective: fair."),
  mcq("vocab-040", "VOCABULARY", "HARD", "The report cites a ___ decline in customer retention.", "precipitous", ["precipitate", "precipitation", "precipitously"], "Adjective modifying 'decline'.", "Adjective: sudden and steep."),
  mcq("vocab-041", "VOCABULARY", "EASY", "The store opens ___ nine o'clock every morning.", "at", ["in", "on", "by"], "Clock times use 'at'.", "Preposition for clock time."),
  mcq("vocab-042", "VOCABULARY", "EASY", "Ms. Lee is responsible ___ coordinating travel arrangements.", "for", ["to", "with", "of"], "Fixed: 'responsible for'.", "Preposition after 'responsible'."),
  mcq("vocab-043", "VOCABULARY", "EASY", "The copier is out of ___; please order more.", "paper", ["papers", "papering", "papered"], "Uncountable in this context.", "Material noun."),
  mcq("vocab-044", "VOCABULARY", "EASY", "All visitors must sign the ___ book at reception.", "guest", ["guests", "guesting", "guested"], "Compound noun 'guest book'.", "Noun modifying 'book'."),
  mcq("vocab-045", "VOCABULARY", "MEDIUM", "The project timeline is subject ___ change.", "to", ["for", "with", "at"], "Fixed phrase 'subject to'.", "Idiom with 'subject'."),
  mcq("vocab-046", "VOCABULARY", "MEDIUM", "Please ___ the attached file for the updated schedule.", "refer to", ["refer", "referring", "reference"], "Phrasal: 'refer to' means look at.", "Phrasal verb + object."),
  mcq("vocab-047", "VOCABULARY", "MEDIUM", "The factory has strict ___ for quality control.", "protocols", ["protocol", "protocoled", "protocoling"], "Plural after 'strict'.", "Plural noun."),
  mcq("vocab-048", "VOCABULARY", "MEDIUM", "Employees are encouraged to ___ suggestions to HR.", "submit", ["submission", "submitted", "submitting"], "To-infinitive after 'encouraged to'.", "Base verb after 'to'."),
  mcq("vocab-049", "VOCABULARY", "HARD", "The firm's ___ approach reduced operational costs.", "streamlined", ["streamline", "streamlining", "streamliner"], "Past participle as adjective.", "Adjective: simplified and efficient."),
  mcq("vocab-050", "VOCABULARY", "HARD", "Contractors must ___ with all safety regulations.", "comply", ["compliance", "compliant", "complying"], "'Comply with' is the correct collocation.", "Verb + 'with' for rules."),
];

const grammar: Q[] = [
  mcq("grammar-001", "GRAMMAR", "EASY", "The presentation ___ at 2 p.m. tomorrow.", "will begin", ["begin", "began", "beginning"], "Future time 'tomorrow' requires future tense.", "Match tense to 'tomorrow'."),
  mcq("grammar-002", "GRAMMAR", "EASY", "Ms. Park ___ in the accounting department since 2019.", "has worked", ["work", "worked", "working"], "Since + point in time → present perfect.", "'Since 2019' signals present perfect."),
  mcq("grammar-003", "GRAMMAR", "EASY", "Neither the manager nor the assistants ___ available.", "are", ["is", "was", "be"], "With 'nor', verb agrees with nearer plural subject.", "Agreement with nearer subject."),
  mcq("grammar-004", "GRAMMAR", "EASY", "Please send the documents ___ you finish reviewing them.", "when", ["which", "who", "whose"], "'When' introduces a time clause.", "Time conjunction."),
  mcq("grammar-005", "GRAMMAR", "EASY", "The report ___ by the team last week.", "was completed", ["completed", "completing", "completes"], "Passive past: was + past participle.", "Passive voice in past."),
  mcq("grammar-006", "GRAMMAR", "EASY", "We look forward ___ meeting you in person.", "to meeting", ["to meet", "meeting", "meet"], "'Look forward to' + gerund.", "Gerund after 'look forward to'."),
  mcq("grammar-007", "GRAMMAR", "EASY", "There ___ several errors in the first draft.", "are", ["is", "was", "be"], "'Several errors' is plural.", "Plural subject 'errors'."),
  mcq("grammar-008", "GRAMMAR", "EASY", "He asked whether we ___ the venue yet.", "had booked", ["book", "booking", "books"], "Reported speech: past perfect for earlier action.", "Past perfect in reported question."),
  mcq("grammar-009", "GRAMMAR", "EASY", "The laptop, along with the cables, ___ in the cabinet.", "is", ["are", "were", "be"], "Subject is singular 'laptop'.", "Singular subject despite 'along with'."),
  mcq("grammar-010", "GRAMMAR", "EASY", "If it ___ tomorrow, the outdoor event will be canceled.", "rains", ["rain", "rained", "raining"], "First conditional: if + present, will + base.", "Present in if-clause."),
  mcq("grammar-011", "GRAMMAR", "MEDIUM", "The contract must ___ by both parties before execution.", "be signed", ["sign", "signed", "signing"], "Modal passive: must be + past participle.", "Passive after modal."),
  mcq("grammar-012", "GRAMMAR", "MEDIUM", "Not only did she finish early, ___ she also checked the figures.", "but", ["and", "so", "yet"], "Correlative: 'Not only... but also'.", "Second part of correlative pair."),
  mcq("grammar-013", "GRAMMAR", "MEDIUM", "The seminar is worth attending, ___ the high registration fee.", "despite", ["although", "however", "because"], "'Despite' + noun phrase.", "Preposition + noun."),
  mcq("grammar-014", "GRAMMAR", "MEDIUM", "By the time you arrive, we ___ the setup.", "will have finished", ["finish", "finished", "will finish"], "Future perfect for action before future point.", "Completion before future time."),
  mcq("grammar-015", "GRAMMAR", "MEDIUM", "The candidate whom we ___ last week accepted the offer.", "interviewed", ["interview", "interviews", "interviewing"], "Past action in relative clause.", "Past tense verb."),
  mcq("grammar-016", "GRAMMAR", "MEDIUM", "Hardly ___ the meeting started when the fire alarm rang.", "had", ["has", "have", "was"], "'Hardly had... when' inversion.", "Inversion after 'hardly'."),
  mcq("grammar-017", "GRAMMAR", "MEDIUM", "Each of the applicants ___ required to bring identification.", "is", ["are", "were", "be"], "'Each' is singular.", "Singular verb with 'each'."),
  mcq("grammar-018", "GRAMMAR", "MEDIUM", "The more carefully you proofread, ___ mistakes you will find.", "the fewer", ["few", "fewer", "the less"], "Comparative parallel: the more..., the fewer...", "Double comparative structure."),
  mcq("grammar-019", "GRAMMAR", "MEDIUM", "I would appreciate it if you ___ me informed.", "kept", ["keep", "keeping", "keeps"], "Subjunctive-like past after 'would appreciate if'.", "Past form in polite request."),
  mcq("grammar-020", "GRAMMAR", "MEDIUM", "The data ___ analyzed before the board meeting.", "was", ["were", "are", "be"], "'Data' often treated as singular in business English.", "Singular verb with 'data' here."),
  mcq("grammar-021", "GRAMMAR", "HARD", "Scarcely ___ the announcement been made when shares surged.", "had", ["has", "have", "was"], "Inversion: Scarcely had...", "Inversion with 'scarcely'."),
  mcq("grammar-022", "GRAMMAR", "HARD", "The proposal, ___ was revised twice, finally gained approval.", "which", ["who", "whom", "whose"], "Non-restrictive clause for things uses 'which'.", "Relative pronoun for things."),
  mcq("grammar-023", "GRAMMAR", "HARD", "Were it not for her intervention, the deal ___ collapsed.", "would have", ["will have", "had", "has"], "Subjunctive conditional past.", "Unreal past conditional."),
  mcq("grammar-024", "GRAMMAR", "HARD", "No sooner ___ the email sent than replies flooded in.", "was", ["were", "is", "are"], "Inversion: No sooner was...", "Singular inversion."),
  mcq("grammar-025", "GRAMMAR", "HARD", "The manager insisted that every employee ___ the training.", "attend", ["attends", "attended", "attending"], "Subjunctive after 'insisted that': base verb.", "Base verb in that-clause."),
  mcq("grammar-026", "GRAMMAR", "EASY", "She ___ to the office by bus every day.", "goes", ["go", "going", "gone"], "Habitual present: third person -s.", "Simple present habit."),
  mcq("grammar-027", "GRAMMAR", "EASY", "We have already ___ the payment.", "received", ["receive", "receiving", "receives"], "Present perfect: have + past participle.", "Past participle after 'have'."),
  mcq("grammar-028", "GRAMMAR", "EASY", "This is the office ___ I work.", "where", ["which", "who", "whose"], "Relative adverb of place.", "Relative word for place."),
  mcq("grammar-029", "GRAMMAR", "EASY", "Could you tell me where the conference room ___?", "is", ["are", "be", "were"], "Embedded question keeps statement order.", "No inversion in embedded question."),
  mcq("grammar-030", "GRAMMAR", "EASY", "The tickets were ___ expensive for our budget.", "too", ["very", "so", "much"], "'Too' + adjective = excessive.", "Excess meaning."),
  mcq("grammar-031", "GRAMMAR", "MEDIUM", "The committee ___ discussing the budget all morning.", "has been", ["is", "was", "will be"], "Duration with 'all morning' → present perfect continuous.", "Ongoing until now."),
  mcq("grammar-032", "GRAMMAR", "MEDIUM", "The invoice should ___ within thirty days.", "be paid", ["pay", "paid", "paying"], "Passive modal: should be paid.", "Passive after 'should'."),
  mcq("grammar-033", "GRAMMAR", "MEDIUM", "He speaks English fluently, ___ he has never lived abroad.", "although", ["despite", "because", "therefore"], "'Although' + clause contrasts ideas.", "Contrast conjunction + clause."),
  mcq("grammar-034", "GRAMMAR", "MEDIUM", "Either Ms. Gomez or Mr. Chen ___ the presentation.", "will give", ["give", "gives", "giving"], "Verb agrees with nearer subject.", "Agreement with nearer subject."),
  mcq("grammar-035", "GRAMMAR", "MEDIUM", "The package arrived ___ than we expected.", "later", ["late", "latest", "lately"], "Comparative adverb.", "Comparative form."),
  mcq("grammar-036", "GRAMMAR", "HARD", "Little ___ that the policy would change so quickly.", "did they realize", ["they realized", "they realize", "they had realized"], "Negative inversion: Little did they...", "Inversion after 'little'."),
  mcq("grammar-037", "GRAMMAR", "HARD", "The project is scheduled to be completed by next month, ___ delays occur.", "unless", ["if", "when", "since"], "'Unless' = if not.", "Conditional unless."),
  mcq("grammar-038", "GRAMMAR", "HARD", "It is essential that the report ___ accurate.", "be", ["is", "was", "being"], "Subjunctive after 'essential that'.", "Base verb subjunctive."),
  mcq("grammar-039", "GRAMMAR", "HARD", "The number of applicants ___ increased this year.", "has", ["have", "are", "were"], "'The number' is singular.", "Singular 'number'."),
  mcq("grammar-040", "GRAMMAR", "HARD", "Not until Monday ___ the final version approved.", "was", ["were", "is", "are"], "Inversion after 'Not until'.", "Inversion structure."),
  mcq("grammar-041", "GRAMMAR", "EASY", "I ___ see you at the trade fair next month.", "will", ["am", "was", "been"], "Future with 'next month'.", "Future marker."),
  mcq("grammar-042", "GRAMMAR", "EASY", "The files are ___ the shared drive.", "on", ["in", "at", "by"], "Digital location often 'on' a drive.", "Preposition for platform."),
  mcq("grammar-043", "GRAMMAR", "EASY", "Who ___ the keynote speech last year?", "gave", ["give", "giving", "given"], "Past time 'last year'.", "Simple past."),
  mcq("grammar-044", "GRAMMAR", "EASY", "We need ___ copies for every participant.", "enough", ["enoughly", "muchly", "many"], "'Enough' before plural countable noun.", "Quantifier before noun."),
  mcq("grammar-045", "GRAMMAR", "MEDIUM", "The workshop was cancelled owing ___ low enrollment.", "to", ["for", "of", "with"], "Fixed: 'owing to'.", "Preposition phrase."),
  mcq("grammar-046", "GRAMMAR", "MEDIUM", "Had I known about the traffic, I ___ earlier.", "would have left", ["leave", "left", "will leave"], "Third conditional inversion.", "Unreal past result."),
  mcq("grammar-047", "GRAMMAR", "MEDIUM", "The CEO, as well as the directors, ___ attending.", "is", ["are", "were", "be"], "Subject 'CEO' is singular.", "Singular main subject."),
  mcq("grammar-048", "GRAMMAR", "MEDIUM", "Please do not hesitate to contact us should you ___ questions.", "have", ["has", "had", "having"], "Formal: 'should you have'.", "Subjunctive-like 'should'."),
  mcq("grammar-049", "GRAMMAR", "HARD", "Seldom ___ such a thorough analysis.", "do we see", ["we see", "we saw", "we have seen"], "Inversion after 'seldom'.", "Auxiliary inversion."),
  mcq("grammar-050", "GRAMMAR", "HARD", "The goods ___ delivered by Friday at the latest.", "are to be", ["is to be", "are being", "was to be"], "Plural 'goods' + scheduled passive.", "Formal scheduled passive."),
];

const reading: Q[] = [
  mcq("reading-001", "READING", "EASY", "What is the main purpose of the notice?", "To inform staff about parking changes", ["To announce a holiday party", "To request vacation forms", "To advertise a sale"], "The notice focuses on parking policy updates.", "Look for the primary topic.", "NOTICE: Starting Monday, employee parking will move to Lot C. Please update your permit at the security desk.", null),
  mcq("reading-002", "READING", "EASY", "When does the new policy take effect?", "Monday", ["Friday", "Next month", "Immediately today"], "The notice states 'Starting Monday'.", "Find the start date.", "NOTICE: Starting Monday, employee parking will move to Lot C.", null),
  mcq("reading-003", "READING", "EASY", "Where should employees update their permits?", "At the security desk", ["At Lot C", "At the HR office", "Online only"], "Permits are updated at the security desk.", "Location for permit update.", "Please update your permit at the security desk.", null),
  mcq("reading-004", "READING", "EASY", "What product is being advertised?", "Office chairs", ["Computer monitors", "Desk lamps", "Filing cabinets"], "The email promotes ergonomic office chairs.", "Product mentioned in subject.", "Email: Save 20% on ergonomic office chairs this week only.", null),
  mcq("reading-005", "READING", "EASY", "How long is the discount available?", "This week only", ["All month", "One day", "Until next year"], "'This week only' limits the offer.", "Duration of promotion.", "Save 20% on ergonomic office chairs this week only.", null),
  mcq("reading-006", "READING", "MEDIUM", "Why was the shipment delayed?", "Because of a customs inspection", ["Because of a typhoon", "Because the order was cancelled", "Because the warehouse closed"], "The memo cites customs inspection.", "Reason for delay.", "Memo: Your order was held for a routine customs inspection and will ship tomorrow.", null),
  mcq("reading-007", "READING", "MEDIUM", "When will the order ship?", "Tomorrow", ["Today", "Next week", "It will not ship"], "The memo says it will ship tomorrow.", "Shipping timeline.", "Your order was held for a routine customs inspection and will ship tomorrow.", null),
  mcq("reading-008", "READING", "MEDIUM", "What should recipients do if they cannot attend?", "Reply by Thursday", ["Call the help desk", "Send payment", "Visit the branch"], "RSVP instructions say reply by Thursday.", "Follow RSVP instructions.", "Invitation: Please reply by Thursday if you cannot attend the quarterly review.", null),
  mcq("reading-009", "READING", "MEDIUM", "What event is mentioned?", "The quarterly review", ["A product launch", "A training workshop", "A company picnic"], "The invitation is for the quarterly review.", "Event name in invitation.", "Please reply by Thursday if you cannot attend the quarterly review.", null),
  mcq("reading-010", "READING", "MEDIUM", "According to the article, what caused higher sales?", "A new marketing campaign", ["Lower prices only", "A store relocation", "Reduced staff"], "The article links sales growth to the campaign.", "Cause of sales increase.", "Article: Sales rose 15% after the new marketing campaign targeted younger customers.", null),
  mcq("reading-011", "READING", "MEDIUM", "By how much did sales rise?", "15%", ["5%", "50%", "1%"], "The article states sales rose 15%.", "Numeric detail.", "Sales rose 15% after the new marketing campaign.", null),
  mcq("reading-012", "READING", "MEDIUM", "Who is the intended audience of the memo?", "All department heads", ["External clients", "Temporary interns", "Retail customers"], "The memo addresses department heads.", "Salutation indicates audience.", "Memo to All Department Heads: Submit budget proposals by March 1.", null),
  mcq("reading-013", "READING", "MEDIUM", "What is the deadline mentioned?", "March 1", ["March 10", "April 1", "February 15"], "Budget proposals are due March 1.", "Deadline date.", "Submit budget proposals by March 1.", null),
  mcq("reading-014", "READING", "HARD", "What can be inferred about the company's expansion?", "It will create new jobs locally", ["It will reduce headcount", "It will close the main office", "It has already failed"], "The press release mentions hiring locally.", "Inference from hiring plans.", "Press Release: The firm will open a regional hub downtown and hire 200 staff from the local workforce.", null),
  mcq("reading-015", "READING", "HARD", "How many staff will be hired?", "200", ["20", "2,000", "100"], "The release specifies 200 staff.", "Number in text.", "The firm will open a regional hub downtown and hire 200 staff.", null),
  mcq("reading-016", "READING", "HARD", "What is the author's tone toward the policy change?", "Cautiously supportive", ["Strongly opposed", "Indifferent", "Sarcastic"], "The editorial acknowledges benefits but notes risks.", "Tone from word choice.", "Editorial: While the policy should improve efficiency, managers must ensure it does not overburden teams.", null),
  mcq("reading-017", "READING", "HARD", "What concern does the editorial raise?", "Teams may become overburdened", ["Costs will double", "The policy is illegal", "Customers will leave"], "The editorial warns against overburdening teams.", "Stated concern.", "Managers must ensure it does not overburden teams.", null),
  mcq("reading-018", "READING", "EASY", "What is being offered in the email?", "Free shipping", ["Free installation", "A cash refund", "Extended warranty"], "The email advertises free shipping.", "Offer in subject line.", "Email: Enjoy free shipping on all orders over $50 this weekend.", null),
  mcq("reading-019", "READING", "EASY", "What is the minimum order for free shipping?", "$50", ["$25", "$100", "$500"], "Free shipping applies over $50.", "Threshold amount.", "Free shipping on all orders over $50 this weekend.", null),
  mcq("reading-020", "READING", "MEDIUM", "Why is the office closed on Friday?", "For system maintenance", ["For a public holiday", "Due to renovation", "Because of a strike"], "The announcement cites system maintenance.", "Reason for closure.", "Announcement: The office will be closed Friday for scheduled system maintenance.", null),
  mcq("reading-021", "READING", "MEDIUM", "What should employees do during the closure?", "Work remotely if possible", ["Take unpaid leave", "Come to the office", "Cancel all meetings"], "Staff are asked to work remotely.", "Instruction during closure.", "Staff should work remotely if possible during the outage.", null),
  mcq("reading-022", "READING", "MEDIUM", "What does the survey ask about?", "Satisfaction with cafeteria services", ["Interest in gym membership", "Preferred office location", "Travel reimbursement"], "The survey topic is cafeteria services.", "Survey subject.", "Survey: Please rate your satisfaction with cafeteria services.", null),
  mcq("reading-023", "READING", "HARD", "Which statement best summarizes the report?", "Online sales grew while in-store sales declined slightly", ["All channels declined", "In-store sales doubled", "Online sales collapsed"], "The report contrasts channel performance.", "Summary of trends.", "Report: Online sales increased 22% year-over-year, while in-store sales fell 3%.", null),
  mcq("reading-024", "READING", "HARD", "By what percentage did online sales increase?", "22%", ["3%", "12%", "32%"], "Online sales increased 22%.", "Percentage for online channel.", "Online sales increased 22% year-over-year.", null),
  mcq("reading-025", "READING", "HARD", "What action does the letter request?", "Confirmation of attendance", ["Payment of an invoice", "Submission of a resume", "Cancellation of a subscription"], "The letter asks recipients to confirm attendance.", "Requested action.", "Letter: Kindly confirm your attendance at the supplier forum by replying to this message.", null),
  mcq("reading-026", "READING", "EASY", "What is the flyer advertising?", "A job fair", ["A concert", "A furniture sale", "A cooking class"], "The flyer promotes a job fair.", "Event type.", "Flyer: Annual Job Fair — meet recruiters from top companies this Saturday.", null),
  mcq("reading-027", "READING", "EASY", "When is the job fair?", "Saturday", ["Monday", "Next month", "Every day"], "The flyer says 'this Saturday'.", "Day mentioned.", "Annual Job Fair — meet recruiters this Saturday.", null),
  mcq("reading-028", "READING", "EASY", "What should tenants do by the first?", "Pay rent", ["Move out", "Renew leases online", "Schedule inspections"], "The notice reminds tenants to pay rent.", "Tenant obligation.", "Reminder: Rent is due on the first of each month.", null),
  mcq("reading-029", "READING", "EASY", "What item is on sale?", "Printer paper", ["Office chairs", "Coffee machines", "Desk phones"], "The ad highlights printer paper.", "Product on sale.", "Ad: Save 15% on printer paper through Sunday.", null),
  mcq("reading-030", "READING", "MEDIUM", "Why was the webinar rescheduled?", "The presenter became ill", ["The platform crashed permanently", "Tickets sold out", "The topic changed"], "An illness caused the reschedule.", "Reason stated.", "Update: Due to the presenter's illness, the webinar will be held next Tuesday.", null),
  mcq("reading-031", "READING", "MEDIUM", "When is the new webinar date?", "Next Tuesday", ["This Friday", "Next year", "Tomorrow morning"], "The update says next Tuesday.", "New date.", "The webinar will be held next Tuesday.", null),
  mcq("reading-032", "READING", "MEDIUM", "What does the policy require?", "Badge display at all times", ["Paid parking off-site", "Silent phones only", "Weekly reports"], "Badges must be visible.", "Policy requirement.", "Policy: All visitors and staff must display ID badges at all times.", null),
  mcq("reading-033", "READING", "MEDIUM", "Who must follow the badge policy?", "Visitors and staff", ["Contractors only", "Executives only", "Guests without appointments"], "Both visitors and staff are included.", "Scope of policy.", "All visitors and staff must display ID badges.", null),
  mcq("reading-034", "READING", "MEDIUM", "What benefit does the program offer?", "Tuition reimbursement", ["Free housing", "Company cars", "Unlimited vacation"], "The brochure mentions tuition reimbursement.", "Program benefit.", "Brochure: Eligible employees may receive tuition reimbursement for approved courses.", null),
  mcq("reading-035", "READING", "MEDIUM", "Who is eligible?", "Employees in approved courses", ["All retirees", "External vendors", "Temporary interns only"], "Eligible employees in approved courses.", "Eligibility.", "Eligible employees may receive tuition reimbursement for approved courses.", null),
  mcq("reading-036", "READING", "HARD", "What trend does the analyst note?", "Demand is shifting to online channels", ["Stores will all close", "Prices will be fixed", "Staff will be cut in half"], "The analyst describes channel shift.", "Trend described.", "Analyst Note: Consumer demand continues shifting toward online channels.", null),
  mcq("reading-037", "READING", "HARD", "What recommendation is made?", "Invest in digital infrastructure", ["Eliminate customer service", "Stop online sales", "Reduce product quality"], "Investment in digital infrastructure is advised.", "Recommendation.", "We recommend investing in digital infrastructure to meet changing demand.", null),
  mcq("reading-038", "READING", "HARD", "What is the primary concern in the memo?", "Data security during the migration", ["Office cafeteria menus", "Holiday scheduling", "Logo redesign"], "Security during migration is the focus.", "Memo topic.", "Memo: Ensure data security protocols are followed during the system migration.", null),
  mcq("reading-039", "READING", "HARD", "When must protocols be followed?", "During the system migration", ["After retirement", "Only on weekends", "Before hiring"], "During migration is specified.", "Timing.", "Ensure data security protocols are followed during the system migration.", null),
  mcq("reading-040", "READING", "EASY", "What is included with the registration?", "A complimentary lunch", ["A free laptop", "Airfare", "Hotel stay"], "Registration includes lunch.", "Registration perk.", "Registration includes a complimentary lunch and conference materials.", null),
  mcq("reading-041", "READING", "EASY", "What must drivers do in Lot B?", "Display a valid permit", ["Pay hourly cash only", "Park on grass", "Leave engines running"], "Valid permits are required.", "Parking rule.", "Drivers must display a valid permit when parking in Lot B.", null),
  mcq("reading-042", "READING", "MEDIUM", "What caused the refund?", "A duplicate charge", ["A late delivery reward", "A loyalty bonus", "A survey prize"], "Duplicate charge triggered refund.", "Refund reason.", "We issued a refund because your account was charged twice.", null),
  mcq("reading-043", "READING", "MEDIUM", "How will the refund be issued?", "To the original payment method", ["As store credit only", "By check mailed weekly", "In cash at the desk"], "Refund goes to original payment method.", "Refund method.", "The refund will appear on your original payment method within five days.", null),
  mcq("reading-044", "READING", "MEDIUM", "What is the purpose of the agenda?", "To outline topics for the board meeting", ["To list employee birthdays", "To advertise products", "To schedule vacations"], "Agenda lists board meeting topics.", "Document purpose.", "Agenda: Board meeting topics include budget review and succession planning.", null),
  mcq("reading-045", "READING", "MEDIUM", "Which topics are listed?", "Budget review and succession planning", ["Cafeteria hours and parking", "Office plants and decor", "Sports club membership"], "Those two topics appear on the agenda.", "Listed topics.", "Topics include budget review and succession planning.", null),
  mcq("reading-046", "READING", "HARD", "What can be inferred about Q3 performance?", "It exceeded internal forecasts", ["It missed all targets", "It was never measured", "It caused layoffs"], "Beating forecasts is stated.", "Performance inference.", "Q3 results exceeded internal forecasts across all regions.", null),
  mcq("reading-047", "READING", "HARD", "Where did performance improve?", "Across all regions", ["In one city only", "Only online", "Only overseas"], "All regions improved.", "Geographic scope.", "Q3 results exceeded internal forecasts across all regions.", null),
  mcq("reading-048", "READING", "HARD", "What limitation does the contract note?", "Either party may terminate with 30 days' notice", ["No termination is allowed", "Only the buyer may cancel", "Termination requires a court order"], "30-day notice termination clause.", "Contract term.", "Either party may terminate this agreement with thirty days' written notice.", null),
  mcq("reading-049", "READING", "EASY", "What should readers do after finishing the manual?", "Complete the short quiz", ["Submit a resume", "Purchase equipment", "Book travel"], "A quiz follows the manual.", "Next step.", "After reading the manual, complete the short quiz to receive credit.", null),
  mcq("reading-050", "READING", "MEDIUM", "What reward is offered for completing the quiz?", "Training credit", ["A cash bonus", "Free parking for a year", "A company car"], "Credit is awarded.", "Completion reward.", "Complete the short quiz to receive training credit.", null),
];

const listening: Q[] = [
  mcq("listening-001", "LISTENING", "EASY", "What will the speaker do next?", "Start the presentation", ["Cancel the meeting", "Leave the room", "Order lunch"], "The speaker says 'Let's begin'.", "Listen for next action.", null, "Good morning everyone. Thank you for coming. We have a lot to cover today, so let's begin."),
  mcq("listening-002", "LISTENING", "EASY", "Where does this announcement likely take place?", "At an airport", ["At a restaurant", "In a library", "At a gym"], "Gate changes are announced at airports.", "Context clues: gate, boarding.", null, "Attention passengers: Flight 302 to Tokyo is now boarding at Gate 12."),
  mcq("listening-003", "LISTENING", "EASY", "Which gate should passengers go to?", "Gate 12", ["Gate 2", "Gate 20", "Gate 22"], "The announcement says Gate 12.", "Specific gate number.", null, "Flight 302 to Tokyo is now boarding at Gate 12."),
  mcq("listening-004", "LISTENING", "EASY", "What is the woman asking about?", "The meeting time", ["The lunch menu", "A printer problem", "A hotel reservation"], "She asks 'What time does the meeting start?'", "Question about schedule.", null, "W: Excuse me, what time does the meeting start? M: It starts at three sharp."),
  mcq("listening-005", "LISTENING", "EASY", "When does the meeting start?", "At 3:00", ["At 2:00", "At 4:00", "At 3:30"], "The man says 'three sharp'.", "Exact time given.", null, "M: It starts at three sharp."),
  mcq("listening-006", "LISTENING", "MEDIUM", "Why is the man calling?", "To reschedule an appointment", ["To place a food order", "To report a fire", "To apply for a job"], "He asks to move the appointment to Friday.", "Purpose of call.", null, "M: Hi, this is Mr. Lopez. I need to reschedule my appointment from Wednesday to Friday afternoon."),
  mcq("listening-007", "LISTENING", "MEDIUM", "Which day does he prefer?", "Friday", ["Wednesday", "Monday", "Sunday"], "He requests Friday afternoon.", "Preferred day.", null, "I need to reschedule my appointment from Wednesday to Friday afternoon."),
  mcq("listening-008", "LISTENING", "MEDIUM", "What problem does the woman mention?", "The copier is jammed", ["The phone line is dead", "The elevator is stuck", "The lights are out"], "She says the copier is jammed again.", "Stated problem.", null, "W: The copier is jammed again. Could maintenance take a look before the rush?"),
  mcq("listening-009", "LISTENING", "MEDIUM", "Who does she want to help?", "Maintenance staff", ["Security", "IT support", "Cleaning crew"], "She asks maintenance to take a look.", "Who should respond.", null, "Could maintenance take a look before the rush?"),
  mcq("listening-010", "LISTENING", "MEDIUM", "What does the speaker recommend?", "Arriving early for registration", ["Skipping the keynote", "Bringing food", "Parking on the street"], "Arrive thirty minutes early for registration.", "Recommendation given.", null, "Welcome to the conference. Please arrive thirty minutes early tomorrow for registration and badge pickup."),
  mcq("listening-011", "LISTENING", "MEDIUM", "How early should attendees arrive?", "30 minutes", ["10 minutes", "One hour", "Two hours"], "Thirty minutes early is advised.", "Time before event.", null, "Please arrive thirty minutes early tomorrow for registration."),
  mcq("listening-012", "LISTENING", "MEDIUM", "What will happen this afternoon?", "A delivery will arrive", ["The office will close", "A interview will be cancelled", "A flight will depart"], "A shipment is due this afternoon.", "Scheduled event.", null, "M: Heads up—the shipment from Denver is due this afternoon around two."),
  mcq("listening-013", "LISTENING", "HARD", "What is the man's opinion of the proposal?", "He thinks it needs more data", ["He fully supports it", "He wants to reject it immediately", "He has not read it"], "He says they need more data before deciding.", "Opinion in response.", null, "W: Should we approve the proposal today? M: I'd rather wait until we have more data from the pilot test."),
  mcq("listening-014", "LISTENING", "HARD", "What does the woman suggest doing?", "Extending the deadline", ["Firing a contractor", "Closing the branch", "Buying new software"], "She proposes pushing the deadline back a week.", "Her suggestion.", null, "W: Could we push the deadline back a week? M: That might work if the client agrees."),
  mcq("listening-015", "LISTENING", "HARD", "What condition does the man mention?", "The client must agree", ["Payment must be made", "Weather must improve", "Staff must travel"], "He says it might work if the client agrees.", "Condition stated.", null, "M: That might work if the client agrees."),
  mcq("listening-016", "LISTENING", "EASY", "What is being announced?", "A store closing early", ["A new product launch", "A job opening", "A price increase"], "The store will close at six tonight.", "Main announcement.", null, "Attention shoppers: The store will close at six tonight for inventory."),
  mcq("listening-017", "LISTENING", "EASY", "Why will the store close early?", "For inventory", ["For a holiday", "Because of weather", "For renovation"], "Closing is for inventory.", "Reason given.", null, "The store will close at six tonight for inventory."),
  mcq("listening-018", "LISTENING", "MEDIUM", "What does the man want to know?", "Whether the report was sent", ["Where the cafeteria is", "Who won the contract", "When the train leaves"], "He asks if she sent the report.", "Information sought.", null, "M: Did you send the quarterly report to the board yet? W: I finished it, but I haven't emailed it."),
  mcq("listening-019", "LISTENING", "MEDIUM", "Has the report been emailed?", "Not yet", ["Yes, this morning", "It was cancelled", "It was lost"], "She hasn't emailed it yet.", "Status of email.", null, "W: I finished it, but I haven't emailed it."),
  mcq("listening-020", "LISTENING", "MEDIUM", "Where is the conversation taking place?", "At a hotel front desk", ["At a factory", "On an airplane", "In a classroom"], "Check-in and room keys suggest a hotel.", "Setting clues.", null, "W: Welcome to the Grand Plaza. Do you have a reservation? M: Yes, under the name Chen."),
  mcq("listening-021", "LISTENING", "HARD", "What will the team do first?", "Review the budget figures", ["Sign the contract", "Book flights", "Hire consultants"], "The leader says they'll start with the budget.", "First step in plan.", null, "Let's start with the budget figures, then we'll discuss staffing."),
  mcq("listening-022", "LISTENING", "HARD", "What will they discuss after the budget?", "Staffing", ["Marketing colors", "Office furniture", "Cafeteria menus"], "After budget, they'll discuss staffing.", "Second agenda item.", null, "Let's start with the budget figures, then we'll discuss staffing."),
  mcq("listening-023", "LISTENING", "HARD", "What is implied about the project timeline?", "It is tight", ["It has been extended", "It was cancelled", "It hasn't started"], "The speaker says they're running out of time.", "Implied urgency.", null, "We're running out of time, so please keep your updates brief."),
  mcq("listening-024", "LISTENING", "EASY", "What should listeners do?", "Turn off mobile phones", ["Take a survey", "Buy tickets", "Submit homework"], "Phones should be silenced during the session.", "Instruction given.", null, "Please silence your mobile phones during the session."),
  mcq("listening-025", "LISTENING", "MEDIUM", "What transportation change is announced?", "The shuttle bus route has changed", ["Trains are cancelled", "Flights are delayed", "Taxis are free"], "The shuttle route has changed.", "Transport update.", null, "Notice: The shuttle bus route has changed. Pickup is now at the north entrance."),
  mcq("listening-026", "LISTENING", "EASY", "What does the speaker ask employees to do?", "Update their passwords", ["Work overtime", "Cancel meetings", "Take a vacation"], "Password update is requested.", "Instruction given.", null, "Please update your passwords by the end of the day for security."),
  mcq("listening-027", "LISTENING", "EASY", "By when should passwords be updated?", "By the end of the day", ["Next month", "Never", "In two weeks"], "End of the day deadline.", "Deadline phrase.", null, "Please update your passwords by the end of the day."),
  mcq("listening-028", "LISTENING", "EASY", "Where is the woman?", "In a coffee shop", ["At a airport gate", "In a hospital", "On a boat"], "She orders a latte.", "Setting clues.", null, "W: I'd like a medium latte to go, please. M: Sure, that'll be ready in a minute."),
  mcq("listening-029", "LISTENING", "EASY", "What does she order?", "A medium latte", ["A sandwich", "A salad", "Tea only"], "She asks for a medium latte.", "Order detail.", null, "W: I'd like a medium latte to go, please."),
  mcq("listening-030", "LISTENING", "MEDIUM", "Why is the man calling IT support?", "His computer won't connect to the network", ["He lost his badge", "He needs vacation approval", "He wants catering"], "Network connection issue.", "Problem described.", null, "M: My laptop won't connect to the network after the update."),
  mcq("listening-031", "LISTENING", "MEDIUM", "When did the problem start?", "After an update", ["After a holiday", "After a promotion", "After lunch only"], "Problem began after the update.", "Timing clue.", null, "My laptop won't connect to the network after the update."),
  mcq("listening-032", "LISTENING", "MEDIUM", "What does the tour guide mention?", "Photography is not allowed in the gallery", ["Food is free", "Tickets are refundable", "The exit is locked"], "No photography rule.", "Rule announced.", null, "Guide: Photography is not allowed in the gallery, but you may take pictures in the courtyard."),
  mcq("listening-033", "LISTENING", "MEDIUM", "Where may visitors take pictures?", "In the courtyard", ["In the gallery", "In the storage room", "Nowhere"], "Courtyard is permitted.", "Allowed location.", null, "You may take pictures in the courtyard."),
  mcq("listening-034", "LISTENING", "MEDIUM", "What will happen at noon?", "The keynote will begin", ["The building will close", "Lunch will be cancelled", "Registration will open"], "Keynote starts at noon.", "Scheduled event.", null, "The keynote will begin at noon in the main hall."),
  mcq("listening-035", "LISTENING", "MEDIUM", "Where will the keynote take place?", "In the main hall", ["At the airport", "In the parking lot", "Online only"], "Main hall location.", "Venue stated.", null, "The keynote will begin at noon in the main hall."),
  mcq("listening-036", "LISTENING", "HARD", "What is the woman's main concern?", "The timeline is too aggressive", ["The budget is too large", "The venue is too small", "The food is too spicy"], "She says the timeline is too aggressive.", "Concern expressed.", null, "W: I'm worried the timeline is too aggressive given the staffing constraints."),
  mcq("listening-037", "LISTENING", "HARD", "What constraint does she mention?", "Staffing", ["Weather", "Currency", "Advertising"], "Staffing constraints cited.", "Constraint type.", null, "Given the staffing constraints, the timeline is too aggressive."),
  mcq("listening-038", "LISTENING", "HARD", "What does the man propose?", "Phasing the rollout in two stages", ["Canceling the project", "Hiring no one", "Launching overnight"], "Two-stage rollout proposed.", "Proposal made.", null, "M: What if we phase the rollout in two stages instead?"),
  mcq("listening-039", "LISTENING", "HARD", "How does the woman respond?", "She thinks it could work", ["She rejects it immediately", "She leaves the room", "She increases the budget"], "She says it could work.", "Response tone.", null, "W: That could work if we communicate clearly to stakeholders."),
  mcq("listening-040", "LISTENING", "EASY", "What number should callers dial?", "Extension 220", ["Extension 002", "Extension 22", "Extension 2020"], "Extension 220 given.", "Extension number.", null, "For billing questions, please dial extension 220."),
  mcq("listening-041", "LISTENING", "EASY", "What department handles billing questions?", "Accounting", ["Marketing", "Security", "Facilities"], "Billing → accounting context.", "Department inferred.", null, "For billing questions, please dial extension 220 in accounting."),
  mcq("listening-042", "LISTENING", "MEDIUM", "What is the man looking for?", "The HR office", ["The cafeteria", "The loading dock", "The roof"], "He asks for directions to HR.", "Destination sought.", null, "M: Excuse me, could you tell me where the HR office is?"),
  mcq("listening-043", "LISTENING", "MEDIUM", "Where is HR located?", "On the second floor", ["In the basement", "Across the street", "At the airport"], "Second floor direction.", "Location answer.", null, "W: HR is on the second floor, room 204."),
  mcq("listening-044", "LISTENING", "MEDIUM", "What problem does the announcement address?", "Elevator maintenance", ["Fire drill", "Power upgrade", "Parking fees"], "Elevator maintenance announced.", "Topic of announcement.", null, "Elevator maintenance will occur from 2 to 4 p.m. Please use the stairs."),
  mcq("listening-045", "LISTENING", "MEDIUM", "What should people use instead?", "The stairs", ["The windows", "The shuttle", "The roof"], "Use stairs during maintenance.", "Alternative instructed.", null, "Please use the stairs during maintenance."),
  mcq("listening-046", "LISTENING", "HARD", "What does the speaker imply about attendance?", "Attendance may be lower than usual", ["Everyone cancelled", "Attendance doubled", "Only VIPs may attend"], "Bad weather may reduce attendance.", "Implied outcome.", null, "With the storm warning, we should expect lower attendance than usual."),
  mcq("listening-047", "LISTENING", "HARD", "Why might attendance be affected?", "A storm warning", ["A pay raise", "A product launch", "A holiday bonus"], "Storm warning cited.", "Cause stated.", null, "With the storm warning, we should expect lower attendance."),
  mcq("listening-048", "LISTENING", "HARD", "What backup plan is mentioned?", "Streaming the session online", ["Closing permanently", "Moving abroad", "Canceling all sales"], "Online stream as backup.", "Contingency plan.", null, "If needed, we'll stream the session online for remote participants."),
  mcq("listening-049", "LISTENING", "EASY", "What should passengers remember?", "To keep their belongings with them", ["To run on the platform", "To leave bags unattended", "To smoke in the cabin"], "Keep belongings with you.", "Safety reminder.", null, "Please keep your belongings with you at all times."),
  mcq("listening-050", "LISTENING", "MEDIUM", "What change affects tomorrow's schedule?", "The client visit was moved to the afternoon", ["The office is closed all week", "All meetings were cancelled", "The CEO resigned"], "Visit moved to afternoon.", "Schedule change.", null, "Update: The client visit was moved to the afternoon due to traffic concerns."),
];

const business: Q[] = [
  mcq("business-001", "BUSINESS_ENGLISH", "EASY", "Choose the best response to: 'Could you send me the agenda?'", "Certainly, I will email it shortly.", ["No, I am agenda.", "Agenda is send now.", "I agenda you."], "Professional polite confirmation.", "Polite offer to send."),
  mcq("business-002", "BUSINESS_ENGLISH", "EASY", "Which subject line is most appropriate for a meeting confirmation?", "Confirmation: Strategy Meeting on April 5", ["Hey!!!", "Stuff", "???"], "Clear, professional subject with topic and date.", "Formal subject line."),
  mcq("business-003", "BUSINESS_ENGLISH", "EASY", "In an email, how should you address an unknown recipient formally?", "Dear Sir or Madam,", ["Hey you,", "Yo,", "What's up,"], "Standard formal salutation.", "Formal greeting."),
  mcq("business-004", "BUSINESS_ENGLISH", "EASY", "Which closing is appropriate for a business letter?", "Sincerely,", ["Love,", "Later,", "Ciao babe,"], "'Sincerely' is standard formal closing.", "Professional sign-off."),
  mcq("business-005", "BUSINESS_ENGLISH", "EASY", "What does 'ASAP' mean in office communication?", "As soon as possible", ["At some actual place", "After sales and profit", "Always stay at post"], "Common abbreviation in business email.", "Standard acronym."),
  mcq("business-006", "BUSINESS_ENGLISH", "MEDIUM", "Which phrase best declines a meeting politely?", "I'm afraid I have a prior commitment that day.", ["No way.", "Go away.", "Meetings are dumb."], "Polite decline with reason.", "Professional refusal."),
  mcq("business-007", "BUSINESS_ENGLISH", "MEDIUM", "In a negotiation, 'We are willing to compromise' means:", "We can accept some changes to reach agreement", ["We will not change anything", "We will leave immediately", "We demand full payment now"], "'Compromise' implies mutual concessions.", "Meaning of compromise."),
  mcq("business-008", "BUSINESS_ENGLISH", "MEDIUM", "Which is the best way to follow up on an unanswered email?", "I wanted to follow up on my message below.", ["Why are you ignoring me?", "Answer me now!!!", "You are rude."], "Neutral professional follow-up.", "Polite follow-up phrasing."),
  mcq("business-009", "BUSINESS_ENGLISH", "MEDIUM", "What does 'net 30' on an invoice mean?", "Payment is due within 30 days", ["A 30% discount applies", "Delivery in 30 hours", "Thirty items included"], "Standard payment term.", "Invoice payment term."),
  mcq("business-010", "BUSINESS_ENGLISH", "MEDIUM", "Which expression best introduces a conference call?", "Let's go ahead and get started.", ["Shut up everyone.", "This is boring.", "I hate calls."], "Neutral facilitator language.", "Call opening phrase."),
  mcq("business-011", "BUSINESS_ENGLISH", "MEDIUM", "In business English, 'touch base' means:", "To make brief contact or check in", ["To play baseball", "To touch a foundation", "To cancel a contract"], "Idiom for short contact.", "Business idiom."),
  mcq("business-012", "BUSINESS_ENGLISH", "MEDIUM", "Which sentence is correct for scheduling?", "Would Thursday at 10 a.m. work for you?", ["Thursday 10 you work?", "You work Thursday maybe?", "10 Thursday is you?"], "Polite question with specific time.", "Scheduling question form."),
  mcq("business-013", "BUSINESS_ENGLISH", "HARD", "What is the purpose of an MOU?", "To outline terms of a preliminary agreement", ["To terminate employment", "To pay taxes", "To ship goods internationally"], "MOU = memorandum of understanding.", "Document purpose."),
  mcq("business-014", "BUSINESS_ENGLISH", "HARD", "Which statement best reflects 'due diligence'?", "Careful investigation before a business decision", ["Ignoring financial records", "Skipping legal review", "Rushing without analysis"], "Due diligence is thorough review.", "Business term definition."),
  mcq("business-015", "BUSINESS_ENGLISH", "HARD", "In email, 'Please find attached' is used to:", "Indicate a file is included with the message", ["Ask the reader to search the office", "Report a lost attachment", "Cancel a shipment"], "Standard attachment phrase.", "Email convention."),
  mcq("business-016", "BUSINESS_ENGLISH", "EASY", "Which reply best accepts a lunch invitation?", "Thank you. I'd be happy to join you.", ["No lunch ever.", "Food is bad.", "I hate you."], "Polite acceptance.", "Accept invitation."),
  mcq("business-017", "BUSINESS_ENGLISH", "EASY", "What should you include when introducing yourself on a call?", "Your name and company", ["Your favorite movie", "Your pet's name", "Your salary"], "Professional introduction basics.", "Call introduction."),
  mcq("business-018", "BUSINESS_ENGLISH", "EASY", "Which word completes: 'Please ___ your availability for next week.'", "confirm", ["confirmation", "confirmed", "confirming"], "Imperative + base verb.", "Verb after 'please'."),
  mcq("business-019", "BUSINESS_ENGLISH", "MEDIUM", "Which phrase signals the end of a presentation?", "That concludes my presentation. Thank you for your attention.", ["I'm done, bye.", "Whatever.", "Stop listening."], "Formal closing remark.", "Presentation ending."),
  mcq("business-020", "BUSINESS_ENGLISH", "MEDIUM", "What does 'FYI' indicate?", "For your information", ["For your invoice", "From your instructor", "Finish your interview"], "Email abbreviation.", "Common acronym."),
  mcq("business-021", "BUSINESS_ENGLISH", "MEDIUM", "Best way to apologize for a delay:", "I apologize for the delay and appreciate your patience.", ["Not my fault.", "Deal with it.", "Delays happen, shrug."], "Professional apology.", "Apology phrasing."),
  mcq("business-022", "BUSINESS_ENGLISH", "MEDIUM", "In a meeting, 'action items' refer to:", "Tasks assigned to be completed after the meeting", ["Snacks served at lunch", "Decorations in the room", "Historical company facts"], "Meeting follow-up tasks.", "Meeting vocabulary."),
  mcq("business-023", "BUSINESS_ENGLISH", "HARD", "Which sentence uses 'leverage' correctly in business?", "We can leverage our brand to enter new markets.", ["We leverage the door open.", "Leverage is a color.", "Please leverage your lunch."], "Business sense: use advantage strategically.", "Business usage of leverage."),
  mcq("business-024", "BUSINESS_ENGLISH", "HARD", "What is an 'elevator pitch'?", "A brief summary of an idea or product", ["A speech given in an elevator malfunction", "A long annual report", "A type of invoice"], "Short persuasive summary.", "Business term."),
  mcq("business-025", "BUSINESS_ENGLISH", "HARD", "Which email best requests a status update?", "Could you please provide an update on the project's progress?", ["Tell me now or else.", "Status???", "Why so slow?"], "Polite status request.", "Professional request."),
  mcq("business-026", "BUSINESS_ENGLISH", "EASY", "Which greeting is appropriate for a known client?", "Dear Ms. Nakamura,", ["Hey Nakamura!!!", "To whom it may never concern,", "Yo client,"], "Formal name salutation.", "Client greeting."),
  mcq("business-027", "BUSINESS_ENGLISH", "EASY", "What does 'EOD' commonly mean?", "End of day", ["End of decade", "Every other day", "Email on demand"], "Standard office abbreviation.", "Acronym meaning."),
  mcq("business-028", "BUSINESS_ENGLISH", "EASY", "Best response when receiving a meeting invite:", "Thank you. I accept the invitation.", ["Ignore it.", "Meetings are useless.", "Why invite me?"], "Polite acceptance.", "Accept invite."),
  mcq("business-029", "BUSINESS_ENGLISH", "MEDIUM", "Which phrase introduces an attachment politely?", "Please find the report attached.", ["Grab the thing.", "Attachment maybe.", "File!!!"], "Standard attachment phrase.", "Attachment intro."),
  mcq("business-030", "BUSINESS_ENGLISH", "MEDIUM", "In negotiations, a 'counteroffer' is:", "A response proposing different terms", ["Immediate agreement", "A legal penalty", "A marketing slogan"], "Counteroffer modifies proposed terms.", "Negotiation term."),
  mcq("business-031", "BUSINESS_ENGLISH", "MEDIUM", "Which sentence sets a clear deadline?", "Please submit your feedback by Friday at 5 p.m.", ["Feedback sometime.", "Friday maybe if you want.", "Do it never."], "Specific day and time.", "Clear deadline."),
  mcq("business-032", "BUSINESS_ENGLISH", "MEDIUM", "What does 'CC' mean on an email?", "Send a copy to additional recipients", ["Cancel the contract", "Confirm the call", "Close the client"], "Carbon copy additional recipients.", "Email field."),
  mcq("business-033", "BUSINESS_ENGLISH", "MEDIUM", "Which is the best way to start a conference call as host?", "Thank you all for joining today.", ["You're late.", "Let's argue.", "I'm tired."], "Professional opener.", "Call opening."),
  mcq("business-034", "BUSINESS_ENGLISH", "MEDIUM", "'Reach out' in business email means:", "To contact someone", ["To stretch your arm", "To reach a destination", "To delete a file"], "Informal phrasal verb for contact.", "Business phrasal verb."),
  mcq("business-035", "BUSINESS_ENGLISH", "HARD", "Which sentence uses ' stakeholders ' appropriately?", "We should update stakeholders before the announcement.", ["Stakeholders are a type of steak.", "Please stakeholders the door.", "Stakeholders only on holidays."], "Stakeholders are interested parties.", "Term usage."),
  mcq("business-036", "BUSINESS_ENGLISH", "HARD", "What is a 'procurement' team responsible for?", "Purchasing goods and services", ["Designing logos", "Writing novels", "Cleaning carpets only"], "Procurement handles purchasing.", "Department role."),
  mcq("business-037", "BUSINESS_ENGLISH", "HARD", "Which closing requests a reply?", "Please let me know if you have any questions.", ["Do not reply ever.", "Questions are banned.", "No communication."], "Invites questions and reply.", "Reply-request closing."),
  mcq("business-038", "BUSINESS_ENGLISH", "EASY", "Which phrase confirms receipt of an email?", "Thank you for your email.", ["What email?", "Go away.", "Never received."], "Acknowledges receipt politely.", "Receipt confirmation."),
  mcq("business-039", "BUSINESS_ENGLISH", "EASY", "Best way to sign off an internal team email:", "Best regards,", ["Forever yours,", "XOXO,", "Smell ya later,"], "Professional internal closing.", "Team email sign-off."),
  mcq("business-040", "BUSINESS_ENGLISH", "MEDIUM", "What does 'PO' stand for in purchasing?", "Purchase order", ["Post office", "Private offer", "Project only"], "Standard purchasing term.", "Purchasing acronym."),
  mcq("business-041", "BUSINESS_ENGLISH", "MEDIUM", "Which phrase delegates a task clearly?", "Could you please handle the vendor calls this week?", ["Do everything forever.", "Maybe sort of try.", "Vendor calls are magic."], "Clear polite delegation.", "Delegation phrasing."),
  mcq("business-042", "BUSINESS_ENGLISH", "MEDIUM", "In a meeting, 'table a discussion' in American English means:", "To postpone discussing it", ["To put it on the table physically", "To approve it immediately", "To cancel the company"], "US usage: postpone the topic.", "Meeting idiom (US)."),
  mcq("business-043", "BUSINESS_ENGLISH", "MEDIUM", "Which subject line is clearest for a shipment delay?", "Update: Shipment Delay — Order #4821", ["Hello!!!", "Stuff happened", "Read this maybe"], "Specific informative subject.", "Clear subject line."),
  mcq("business-044", "BUSINESS_ENGLISH", "HARD", "Which sentence correctly uses ' pursuant to '?", "Pursuant to our agreement, payment is due on receipt.", ["Pursuant the lunch was tasty.", "Pursuant to run fast.", "Pursuant is a color."], "Formal: in accordance with.", "Formal legal/business phrase."),
  mcq("business-045", "BUSINESS_ENGLISH", "HARD", "What is ' ROI '?", "Return on investment", ["Rate of interest only", "Report on inventory", "Reply on invoice"], "Financial performance measure.", "Finance acronym."),
  mcq("business-046", "BUSINESS_ENGLISH", "HARD", "Best way to disagree professionally in a meeting:", "I see your point; however, I'd like to suggest another approach.", ["You're wrong.", "That's stupid.", "No."], "Acknowledge then counter.", "Professional disagreement."),
  mcq("business-047", "BUSINESS_ENGLISH", "EASY", "Which phrase schedules a call?", "Are you available for a brief call tomorrow?", ["Call me now at 3 a.m.", "Never call.", "Phones are bad."], "Polite scheduling question.", "Schedule call."),
  mcq("business-048", "BUSINESS_ENGLISH", "MEDIUM", "What does 'TBD' mean on an agenda?", "To be determined", ["To be deleted", "Total business day", "Try before dinner"], "Placeholder for undecided item.", "Agenda abbreviation."),
  mcq("business-049", "BUSINESS_ENGLISH", "MEDIUM", "Which reply best confirms a reservation?", "Thank you. I confirm the reservation for two on June 10 at 7 p.m.", ["Maybe.", "Reservation is food.", "No details."], "Confirms date, time, party size.", "Reservation confirmation."),
  mcq("business-050", "BUSINESS_ENGLISH", "HARD", "Which email tone is appropriate when rejecting a proposal politely?", "Thank you for the proposal. After careful review, we have decided not to move forward at this time.", ["Your proposal is terrible.", "Rejected!!!", "Try again never."], "Thanks + clear decision + professional tone.", "Polite rejection."),
];

const files: Record<string, Q[]> = {
  vocabulary,
  grammar,
  reading,
  listening,
  business,
};

mkdirSync(OUT_DIR, { recursive: true });

for (const [name, questions] of Object.entries(files)) {
  const path = join(OUT_DIR, `${name}.json`);
  writeFileSync(path, JSON.stringify(questions, null, 2) + "\n");
  console.log(`Wrote ${questions.length} questions → ${path}`);
}

console.log(
  "Total:",
  Object.values(files).reduce((n, q) => n + q.length, 0),
);
