/** Map question keywords → emoji illustration (rendered as Twemoji in the UI). */

const KEYWORD_EMOJI = {
  apple: '🍎',
  ball: '⚽',
  sky: '🌤️',
  grass: '🌿',
  sun: '☀️',
  carrot: '🥕',
  flower: '🌸',
  grape: '🍇',
  bear: '🐻',
  night: '🌙',
  cloud: '☁️',
  leaf: '🍃',
  snow: '❄️',
  chocolate: '🍫',
  fire: '🔥',
  truck: '🚒',
  red: '🔴',
  blue: '🔵',
  green: '🟢',
  yellow: '🟡',
  orange: '🟠',
  pink: '💗',
  purple: '🟣',
  brown: '🟤',
  black: '⚫',
  white: '⚪',
  cat: '🐱',
  kitten: '🐱',
  dog: '🐶',
  puppy: '🐶',
  cow: '🐮',
  duck: '🦆',
  sheep: '🐑',
  pig: '🐷',
  bird: '🐦',
  frog: '🐸',
  horse: '🐴',
  lion: '🦁',
  fish: '🐟',
  elephant: '🐘',
  ant: '🐜',
  bee: '🐝',
  rabbit: '🐰',
  monkey: '🐵',
  banana: '🍌',
  honey: '🍯',
  water: '💧',
  eyes: '👀',
  ears: '👂',
  nose: '👃',
  mouth: '👄',
  hands: '🤲',
  feet: '🦶',
  fingers: '🖐️',
  head: '🧒',
  teeth: '🦷',
  breakfast: '🍳',
  lunch: '🥪',
  dinner: '🍽️',
  bread: '🍞',
  milk: '🥛',
  rice: '🍚',
  egg: '🥚',
  cake: '🎂',
  pizza: '🍕',
  soup: '🍲',
  fruit: '🍎',
  vegetable: '🥦',
  apple: '🍎',
  book: '📖',
  pen: '🖊️',
  pencil: '✏️',
  school: '🏫',
  teacher: '👩‍🏫',
  student: '🧑‍🎓',
  homework: '📝',
  classroom: '🏫',
  bus: '🚌',
  car: '🚗',
  bike: '🚲',
  train: '🚂',
  plane: '✈️',
  boat: '⛵',
  ship: '🚢',
  house: '🏠',
  bed: '🛏️',
  chair: '🪑',
  table: '🪑',
  door: '🚪',
  window: '🪟',
  hat: '🎩',
  shirt: '👕',
  shoes: '👟',
  socks: '🧦',
  coat: '🧥',
  dress: '👗',
  gloves: '🧤',
  scarf: '🧣',
  umbrella: '☂️',
  rain: '🌧️',
  wind: '💨',
  hot: '🔥',
  cold: '❄️',
  happy: '😊',
  sad: '😢',
  run: '🏃',
  jump: '🦘',
  swim: '🏊',
  sing: '🎤',
  dance: '💃',
  play: '🎮',
  toy: '🧸',
  ball: '⚽',
  tree: '🌳',
  forest: '🌲',
  mountain: '🏔️',
  beach: '🏖️',
  ocean: '🌊',
  river: '🏞️',
  moon: '🌙',
  star: '⭐',
  planet: '🪐',
  mars: '🔴',
  scissors: '✂️',
  dentist: '🦷',
  doctor: '🩺',
  pilot: '✈️',
  farmer: '👨‍🌾',
  money: '💰',
  museum: '🏛️',
  music: '🎵',
  football: '⚽',
  museum: '🏛️',
  voyage: '🚢',
  microscope: '🔬',
  astronomy: '🔭',
  bangkok: '🇹🇭',
  thailand: '🇹🇭',
  robot: '🤖',
  computer: '💻',
  password: '🔐',
  podcast: '🎙️',
  poem: '📜',
  novel: '📕',
  biography: '📘',
  democracy: '🗳️',
  constitution: '📜',
  scholarship: '🎓',
  internship: '💼',
  recycling: '♻️',
  sustainability: '🌱',
  photosynthesis: '🌿',
  pacific: '🌊',
  equator: '🌍',
  peninsula: '🏝️',
  islands: '🏝️',
  copyright: '©️',
  phishing: '🎣',
  virtual: '🥽',
  printing: '🖨️',
  cybersecurity: '🛡️',
  entrepreneur: '💡',
  collaboration: '🤝',
  mindfulness: '🧘',
  resilience: '💪',
  refugee: '🕊️',
  inflation: '📈',
  trade: '🤝',
  tariff: '📦',
  networking: '🤝',
  debate: '💬',
  robotics: '🤖',
  variable: '🧪',
  hypothesis: '🔬',
  latitude: '🗺️',
  archipelago: '🏝️',
  gdp: '📊',
  import: '📥',
  export: '📤',
  budget: '💳',
  resume: '📄',
  speaking: '🎤',
  fable: '📖',
  irony: '😏',
  satire: '🎭',
  stanza: '📝',
  rhyme: '🎵',
  buzz: '🐝',
  wind: '💨',
  flashback: '⏪',
  foreshadowing: '🔮',
  protagonist: '🦸',
  resolution: '✅',
  fantasy: '🧙',
  citation: '📎',
  review: '🔍',
  control: '🧫',
  results: '📊',
  decade: '🔟',
  century: '💯',
  synonym: '📖',
  antonym: '↔️',
  prefix: '🔤',
  adjective: '📝',
  noun: '📦',
  adverb: '⚡',
  plagiarism: '⚠️',
  algorithm: '🧮',
  intelligence: '🧠',
  sustainable: '♻️',
  compound: '🔗',
  homophone: '🔊',
  personification: '🗣️',
  genre: '📚',
  fiction: '📖',
  'non-fiction': '📰',
  onomatopoeia: '💥',
};

const SORTED_KEYS = Object.keys(KEYWORD_EMOJI).sort((a, b) => b.length - a.length);

const TOPIC_RULES = [
  [/grammar|correct sentence|past of|plural of|tense|___/, '✏️'],
  [/planet|mars|venus|jupiter|astronomy|space|red planet/, '🪐'],
  [/photosynthesis|biology|experiment|hypothesis|variable|control group/, '🔬'],
  [/ocean|pacific|h2o|river|water/, '🌊'],
  [/plant|tree|flower|recycle|sustainable/, '🌱'],
  [/country|capital|bangkok|map|latitude|longitude|equator|peninsula|archipelago/, '🌍'],
  [/computer|code|algorithm|cyber|robot|software|phishing|password/, '💻'],
  [/story|poem|book|biography|novel|fable|stanza|rhyme/, '📖'],
  [/number|math|decade|century|\d+/, '🔢'],
  [/democracy|government|constitution|trade|tariff|gdp|inflation|budget/, '🏛️'],
  [/music|listen/, '🎵'],
  [/homework|school|study|scholarship/, '📚'],
  [/rain|weather|if it rains/, '🌧️'],
  [/money|don\'t have any/, '💰'],
  [/sleep|sofa|bed/, '🛋️'],
  [/museum|tomorrow/, '🏛️'],
  [/football|sport|play/, '⚽'],
  [/feeling|empathy|nervous|anxious/, '💭'],
  [/opposite|antonym/, '↔️'],
  [/synonym/, '📖'],
  [/cut paper|scissors/, '✂️'],
  [/teeth|dentist/, '🦷'],
  [/ship|voyage/, '🚢'],
  [/microscopic|tiny|small/, '🔬'],
  [/store|save/, '📦'],
  [/whisper|quiet/, '🤫'],
  [/generous|selfish/, '🎁'],
  [/active voice|passive/, '📝'],
  [/copyright|fair use/, '©️'],
  [/virtual reality|vr/, '🥽'],
  [/3d print/, '🖨️'],
  [/peer review|scientific method/, '🔬'],
  [/public speaking|debate/, '🎤'],
  [/networking|collaboration/, '🤝'],
  [/mindfulness|resilience/, '🧘'],
  [/refugee|human rights/, '🕊️'],
  [/entrepreneur|innovation/, '💡'],
  [/internship|resume|cv/, '💼'],
  [/flashback|foreshadowing|protagonist|resolution/, '📖'],
  [/irony|satire/, '🎭'],
  [/onomatopoeia/, '💥'],
  [/personification/, '🗣️'],
  [/homophone/, '🔊'],
  [/compound word/, '🔗'],
  [/silent letter/, '🔤'],
  [/topic sentence|conclusion|paragraph/, '📝'],
  [/import|export/, '📦'],
  [/open source/, '💻'],
  [/artificial intelligence|ai/, '🤖'],
];

const SKIP_CORRECT_IMAGE = new Set([
  'yes', 'no', 'maybe', 'play', 'listen', 'listens', 'listen', 'finished', 'finish',
  'does', 'do', 'did', 'are', 'is', 'am', 'was', 'were', 'will', 'would', 'already',
  'never', 'ever', 'always', 'yet', 'true', 'false', 'correct', 'wrong',
]);

export function resolveQuestionImage(question, options, correctIndex = 0, band = 'young') {
  const questionLower = question.toLowerCase();
  const correct = String(options[correctIndex] ?? '').toLowerCase().trim();
  const blob = `${question} ${options.join(' ')}`.toLowerCase();

  for (const key of SORTED_KEYS) {
    if (questionLower.includes(key)) return KEYWORD_EMOJI[key];
  }

  if (correct && KEYWORD_EMOJI[correct] && !SKIP_CORRECT_IMAGE.has(correct)) {
    return KEYWORD_EMOJI[correct];
  }

  for (const key of SORTED_KEYS) {
    if (blob.includes(key)) return KEYWORD_EMOJI[key];
  }

  for (const [pattern, emoji] of TOPIC_RULES) {
    if (pattern.test(blob)) return emoji;
  }

  return band === 'junior' ? '🧠' : '⭐';
}

export function attachImageToQuestion(item) {
  const band = item.band || 'young';
  const image = item.image || resolveQuestionImage(item.question, item.options, item.correct_index, band);
  return { ...item, image };
}

export function emojiToImageUrl(emoji) {
  if (!emoji) return null;
  const parts = [];
  for (const char of emoji) {
    const cp = char.codePointAt(0);
    if (cp === 0xfe0f) continue;
    parts.push(cp.toString(16));
  }
  if (!parts.length) return null;
  return `https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/${parts.join('-')}.png`;
}
